### ISSUE TITLE
add Postgres

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/db-benchmarks#17]
Let's add support for Postgres.  
  
The docker-compose service draft is:  
  
```  
  postgres:  
    image: postgres:14.3  
    container_name: "postgres_engine"  
    mem_limit: ${mem}m  
    cpuset: "${cpuset}"  
    privileged: true  
    mem_swappiness: 0  
    ulimits:  
      memlock:  
        soft: -1  
        hard: -1  
      nproc: 65535  
      nofile:  
        soft: 262144  
        hard: 262144  
    ports:  
      - "127.0.0.1:5432:5432"  
    volumes:  
      - ./tests/${test}/postgres/data${suffix}:/var/lib/postgresql/data  
      - ./tests/${test}/data:/input  
    environment:  
      - POSTGRES_HOST_AUTH_METHOD=trust  
      - POSTGRES_DB=default  
```
